import { 
    AllBubbles,
    Bubble
} from './style'

const Bubbles = () => {
    
    const randomDelay = () => {
        return Math.random() * 2
    }

    const randomXPosition = () => {
        return Math.floor(Math.random() * 100)
    }

    const randomDuration = () => {
        return Math.floor(Math.random() * 5) + 1.6
    }

    const randomYPosition = () => {
        return Math.floor(Math.random() * 30) + 160
    }

    return (
        <>
                <AllBubbles>
                    <div>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()}  
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()}  
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()}  
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()}  
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()}  
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()}  
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()}  
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()}  
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()}  
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()}  
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        <Bubble 
                        delay={randomDelay()} 
                        pos={randomXPosition()} 
                        duration={randomDuration()} 
                        top={randomYPosition()}/>
                        
                    </div>
                </AllBubbles>
        </>
    )
}

export default Bubbles
